version: '3.8'

services:
  api:
    container_name: api
    image: node:18-alpine
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - redis
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true 
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - '${DB_HOST_PORT}:${DB_PORT}'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  db_test:
    container_name: test_postgres
    image: postgres:15-alpine
    ports:
      - '${TEST_DB_HOST_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  data:
  redis_data:
